# Generated by Django 5.2.1 on 2025-08-29 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_vendormaster_shipment_boe_num_tripouttovendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='additional_freight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='manifest',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='manifest',
            name='vendor_name',
            field=models.ForeignKey(blank=True, db_column='vendor_name', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manifests', to='main.vendormaster', to_field='vendor_code'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='additional_ref_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='ro_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipment_mode',
            field=models.CharField(choices=[('By_Road', 'By Road'), ('By_Air', 'By Air'), ('By_Train', 'By Train')], default='By_Road', max_length=15),
        ),
        migrations.AddField(
            model_name='shipment',
            name='so_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='boe_num',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_type',
            field=models.CharField(choices=[('PTL', 'PTL'), ('FTL', 'FTL'), ('PTL-RTO', 'PTL-RTO'), ('FTL-RTO', 'FTL-RTO'), ('PTL-APT', 'PTL-APT'), ('PTL-NOR', 'PTL-NOR'), ('FTL-APT', 'FTL-APT'), ('FTL-NOR', 'FTL-NOR')], max_length=15),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Picked-Up', 'Picked-Up'), ('Arrived', 'Arrived'), ('Accepted at Hub', 'Accepted at Hub'), ('In Transit', 'In Transit'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Partial Delivered', 'Partial Delivered'), ('RTO', 'Return to Origin')], default='Booked', max_length=30),
        ),
    ]
