# Generated by Django 5.2.1 on 2025-08-31 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_manifest_additional_freight_manifest_advance_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='item_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipment',
            name='vehicle_type',
            field=models.CharField(choices=[('LCV', 'LCV'), ('TATA-ACE', 'TATA-ACE'), ('Truck-9ft', 'Truck-9ft'), ('Truck-14ft', 'Truck-14ft'), ('Truck-17ft', 'Truck-17ft'), ('Truck-19ft', 'Truck-19ft'), ('Truck-20ft', 'Truck-20ft'), ('Truck-22ft', 'Truck-22ft'), ('Truck-24ft', 'Truck-24ft'), ('Truck-28ft', 'Truck-28ft'), ('Truck-32ft', 'Truck-32ft')], default='LCV', max_length=30),
        ),
        migrations.AddField(
            model_name='shipment',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='main.vendormaster'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Picked-Up', 'Picked-Up'), ('Arrived', 'Arrived'), ('Accepted at Hub', 'Accepted at Hub'), ('In Transit', 'In Transit'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Partial Delivered', 'Partial Delivered'), ('RTO', 'Return to Origin'), ('Delivery Failed', 'Delivery Failed')], default='Booked', max_length=30),
        ),
    ]
