# Generated by Django 5.2.1 on 2025-09-01 01:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_shipment_item_count_shipment_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='balance_freight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pickedup_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
