# Generated by Django 5.2.1 on 2025-09-01 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_manifest_balance_freight_shipment_pickedup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='length_ft',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipment',
            name='total_dfc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipment',
            name='width_ft',
            field=models.IntegerField(default=0),
        ),
    ]
