# Generated by Django 5.2.1 on 2025-09-01 01:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_shipment_length_ft_shipment_total_dfc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='pickedup_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
