# Generated by Django 5.2.1 on 2025-09-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_shipment_pickedup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='height',
            field=models.IntegerField(default=0),
        ),
    ]
