# Generated by Django 5.2.1 on 2025-09-14 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_shipment_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_id', models.CharField(editable=False, max_length=60, unique=True)),
                ('box_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('box_height', models.DecimalField(decimal_places=2, max_digits=8)),
                ('box_length', models.DecimalField(decimal_places=2, max_digits=8)),
                ('box_width', models.DecimalField(decimal_places=2, max_digits=8)),
                ('box_type', models.CharField(max_length=50)),
                ('remark', models.TextField(blank=True, null=True)),
                ('total_volumetric', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='main.shipment')),
            ],
        ),
    ]
