# Generated by Django 5.2.1 on 2025-09-16 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='box_id',
            new_name='batch_id',
        ),
        migrations.AddField(
            model_name='content',
            name='count_of_box',
            field=models.IntegerField(default=0),
        ),
    ]
