# Generated by Django 5.2.1 on 2025-09-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_box_id_content_batch_id_content_count_of_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Confirmed', 'Confirmed'), ('Ready for Pickup', 'Ready for Pickup'), ('Pickup Scheduled', 'Pickup Scheduled'), ('Picked Up', 'Picked Up'), ('Arrived', 'Arrived'), ('Accepted at Hub', 'Accepted at Hub'), ('In Transit', 'In Transit'), ('Reached Origin Hub', 'Reached Origin Hub'), ('Departed Origin Hub', 'Departed Origin Hub'), ('In Transit to Destination', 'In Transit to Destination'), ('Reached Destination Hub', 'Reached Destination Hub'), ('Out For Delivery', 'Out For Delivery'), ('Delivery Attempted', 'Delivery Attempted'), ('Delivered', 'Delivered'), ('Partial Delivered', 'Partial Delivered'), ('Failed Delivery', 'Failed Delivery'), ('Customer Not Available', 'Customer Not Available'), ('Address Issue', 'Address Issue'), ('Refused by Customer', 'Refused by Customer'), ('Damaged', 'Damaged'), ('Lost', 'Lost'), ('On Hold', 'On Hold'), ('Delayed', 'Delayed'), ('Under Investigation', 'Under Investigation'), ('RTO', 'RTO'), ('RTO In Transit', 'RTO In Transit'), ('RTO Delivered', 'RTO Delivered'), ('Cancelled', 'Cancelled'), ('Returned to Sender', 'Returned to Sender')], default='Booked', max_length=30),
        ),
    ]
